### PR TITLE
Update to a new Operator SDK and move to Go modules

### PR DESCRIPTION
**Pull request by stepanstipl**
This PR updates to a new Operator SDK framework, which includes migration to go modules as a package management mechanism and related changes to get the operator working.

**Changes included:**
- Remove vendoring (package version are managed via Go modules)
- Update to Operator SDK 0.14 and move to Go modules
- Update generated code by (new Operator SDK)
- Fix compile errors by updating .client.List to new signature
- Update generated CRD (new Operator SDK)

### CODE REVIEW

**Comment by amatas** [comment]
imagen
amaaazing

**Comment by stepanstipl** [comment]
> amaaazing

It's the deleted vendor directory :)...

**Review by amatas — APPROVED** [review]
LGTM

**Comment by natarajaya** [comment]
LGTM!

**Pull request merged**
