### PR TITLE
Notify feature

### PR DESCRIPTION
**Pull request by stepanstipl**
This PR adds support for "Notification" feature. New `notify` block has been added to the CRD, which allows specifying a list of resources that should be notified when the composite certificate is updated (initially only `Deployment` type is supported).

The core use case is to notify `istio-ingress-gateway`, by updating its pods annotation, trigger a rolling update and therefore certificate reload.

**Changes introduced in this PR**
- Extended CertMerge CRD with `notify`
- Updated depending auto-generated files
- Added notification logic
- Updated documentation
- Make CRD fields `notify`, `selector` and `secretList` option (as was before operator-sdk update)
- Mitigate unnecessary updates of the composite certificate by comparing current a and new value

Tag `v0.0.3-gpii.2` shall be created once this PR is merged.

### CODE REVIEW

**Review by amatas — APPROVED** [review]
Despite I need more time to be familiar with Go language and this operator the main logic looks good to me.

**Comment by amatas** [comment]
Perhaps this improvement can be useful for upstream as well

**Comment by natarajaya** [comment]
Seems like a nice way to rolling restart deployment to force reload on cert update.

LGTM!

**Review by natarajaya — APPROVED** [review]

**Comment by stepanstipl** [comment]
Thanks for reviews 👍 

> Perhaps this improvement can be useful for upstream as well

Yes, I'll open upstream PRs

> Seems like a nice way to rolling restart deployment to force reload on cert update.

Till GKE catches up with Istio version - now you can serve certs directly from K8s secrets.. but it's in 1.4 I believe...

**Pull request merged**
